cmake_minimum_required(VERSION 3.16)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(RV1106_TRIPLE "$ENV{RV1106_TRIPLE}")
if(RV1106_TRIPLE STREQUAL "")
  set(RV1106_TRIPLE arm-linux-gnueabihf)
endif()

set(RV1106_TOOLCHAIN_BIN "$ENV{RV1106_TOOLCHAIN_BIN}")
if(RV1106_TOOLCHAIN_BIN STREQUAL "")
  message(FATAL_ERROR "RV1106_TOOLCHAIN_BIN is not set")
endif()

set(RV1106_SYSROOT "$ENV{RV1106_SYSROOT}")
if(RV1106_SYSROOT STREQUAL "")
  message(FATAL_ERROR "RV1106_SYSROOT is not set")
endif()

set(CMAKE_C_COMPILER   "${RV1106_TOOLCHAIN_BIN}/${RV1106_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${RV1106_TOOLCHAIN_BIN}/${RV1106_TRIPLE}-g++")
set(CMAKE_AR           "${RV1106_TOOLCHAIN_BIN}/${RV1106_TRIPLE}-ar")
set(CMAKE_STRIP        "${RV1106_TOOLCHAIN_BIN}/${RV1106_TRIPLE}-strip")

set(CMAKE_SYSROOT "${RV1106_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH "${RV1106_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
