[env:m5stackc]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit ILI9341
  links2004/WebSockets @ ^2.6.1
  bblanchon/ArduinoJson @ ^7.2.0

build_flags =
  -D VIBE_WOKWI=1
  -D VIBE_DEVICE_NAME=\"Wokwi-Vibe-Remote\"
  -D VIBE_SERVICE_TYPE=\"vibe-remote\"
